import './globals.css'
import { Nunito } from 'next/font/google'
import Navbar from './components/Navbar/Navbar'
import ClientOnly from './components/ClientOnly'
import Modal from './components/modals.tsx/Modal'
import RegisterModal from './components/modals.tsx/RegisterModal'
import ToastProvider from './components/providers/ToastProvider'
import LoginModal from './components/modals.tsx/LoginModal'
import getCurrentUser from './actions/getCurrentUser'
import RentModal from './components/modals.tsx/RentModal'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const font = Nunito({
  subsets: ["latin"]
})

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser=await getCurrentUser()
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
            <ToastProvider/>
            <RegisterModal/>
            <LoginModal/>
            <Navbar currentUser={currentUser}/>
        </ClientOnly>
                {children}
          </body>
    </html>
  )
}
